Break the pipline - failure test

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -13,6 +13,11 @@ jobs:
     steps:
     - name: Checkout repo
       uses: actions/checkout@v3
+      - name: Break the pipeline
+  run: |
+    echo "Failing on purpose"
+    exit 1
+
 
     - name: Run test
       run: |
